version: '3.8'

services:
  db:
    build: .
    container_name: mobile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mobile
      MYSQL_USER: master
      MYSQL_PASSWORD: master
    ports:
      - "3306:3306"
    volumes:
      - ./dump/init.sql:/docker-entrypoint-initdb.d/init.sql
